"""Strategy abstractions and signal models."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Literal

import pandas as pd


SignalAction = Literal["BUY", "SELL"]


class StrategyError(ValueError):
    """Raised when a strategy receives invalid data or parameters."""


@dataclass(frozen=True)
class TradeSignal:
    """A single actionable decision generated by a strategy."""

    ts_code: str
    trade_date: str
    action: SignalAction
    price: float | None = None
    # Optional size cap. ``None`` means "use the executor's own sizing"; an
    # explicit value must be honoured so a manual/simulated order can be smaller
    # than a full position instead of silently going all-in.
    quantity: float | None = None
    strength: float = 1.0
    reason: str = ""
    strategy_id: str = ""
    strategy_version: str = ""
    signal_id: str = ""

    def as_dict(self) -> dict[str, object]:
        return {
            "ts_code": self.ts_code,
            "trade_date": self.trade_date,
            "action": self.action,
            "price": self.price,
            "quantity": self.quantity,
            "strength": self.strength,
            "reason": self.reason,
            "strategy_id": self.strategy_id,
            "strategy_version": self.strategy_version,
            "signal_id": self.signal_id,
        }


class Strategy(ABC):
    """Base class for daily-bar trading strategies."""

    name: str = "base"
    strategy_id: str = "base"
    version: str = "1.0"
    status: str = "experimental"
    enabled: bool = True
    _signal_counter: int = 0

    @abstractmethod
    def generate_signals(self, daily: pd.DataFrame) -> list[TradeSignal]:
        """Generate signals from normalized daily OHLCV data.

        Parameters
        ----------
        daily:
            DataFrame conforming to the ``daily`` data-layer schema.

        Returns
        -------
        list[TradeSignal]
            Signals ordered by ``ts_code`` and ``trade_date``.
        """

    def make_signal(
        self,
        *,
        ts_code: str,
        trade_date: str,
        action: SignalAction,
        price: float | None = None,
        strength: float = 1.0,
        reason: str = "",
    ) -> TradeSignal:
        """Create a signal stamped with strategy metadata and a unique id."""
        # The counter is kept on the class so ids stay unique even when a scan
        # works on a throwaway copy of the strategy; ``self._signal_counter += 1``
        # would shadow it per instance and restart numbering every time.
        cls = type(self)
        cls._signal_counter += 1
        sequence = cls._signal_counter
        signal_id = (
            f"{self.strategy_id}_v{self.version}_{ts_code}_{trade_date}"
            f"_{action}_{sequence}"
        )
        return TradeSignal(
            ts_code=ts_code,
            trade_date=trade_date,
            action=action,
            price=price,
            strength=strength,
            reason=reason,
            strategy_id=self.strategy_id,
            strategy_version=self.version,
            signal_id=signal_id,
        )


def prepare_daily(daily: pd.DataFrame) -> pd.DataFrame:
    """Validate and normalize a daily DataFrame for strategy consumption."""

    required = {"ts_code", "trade_date", "close"}
    missing = required.difference(daily.columns)
    if missing:
        raise StrategyError(f"daily data missing required columns: {sorted(missing)}")

    result = daily.copy()
    result["ts_code"] = result["ts_code"].astype(str)
    result["trade_date"] = result["trade_date"].astype(str)
    result["close"] = pd.to_numeric(result["close"], errors="coerce")

    if result["close"].isna().any():
        raise StrategyError("daily data contains invalid close values")

    return result.sort_values(["ts_code", "trade_date"]).reset_index(drop=True)
